In [34]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import copy

import torch_geometric.nn as pyg_nn
import torch_geometric.utils as pyg_utils

import time
from datetime import datetime

import networkx as nx
import numpy as np
import torch
import torch.optim as optim

from torch_geometric.datasets import TUDataset
from torch_geometric.datasets import Planetoid
from torch_geometric.data import DataLoader
from torch_geometric.utils import from_networkx

import torch_geometric.transforms as T

#from tensorboardX import SummaryWriter
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

In [79]:
# output_dim replaced by 1
output_dim = 1
class GNNStack(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super(GNNStack, self).__init__()
        self.convs = nn.ModuleList()
        self.convs.append(self.build_conv_model(input_dim, hidden_dim))
        for l in range(2):
            self.convs.append(self.build_conv_model(hidden_dim, hidden_dim))

        # post-message-passing
        self.post_mp = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim), nn.Dropout(0.25), 
            nn.Linear(hidden_dim, output_dim))

        self.dropout = 0.25
        self.num_layers = 3

    def build_conv_model(self, input_dim, hidden_dim):
        # refer to pytorch geometric nn module for different implementation of GNNs.
        return pyg_nn.GCNConv(input_dim, hidden_dim)
    
    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        if data.num_node_features == 0:
          x = torch.ones(data.num_nodes, 1)

        for i in range(self.num_layers):
            x = self.convs[i](x, edge_index)
            emb = x
            x = F.relu(x)
            x = F.dropout(x, p=self.dropout, training=self.training)

        x = self.post_mp(x)
        return x

    def loss(self, pred, actual):
        return F.mse_loss(pred, actual)

In [22]:
LG = nx.read_graphml('experiments/preprocessed/san_francisco.graphml')

In [83]:
LG = nx.read_graphml('experiments/preprocessed/san_francisco.graphml')
node_feature_list = ['speed_mph_p85', 'length', 'oneway']
edge_feature_list = ['x','y']

lg_node_attr = {}
node_relabel = {}

IDs = {}
cur_ID = 0

#To make torch_geometric.data extraction easier, remove every node that doesn't have ALL of the features in node_feature_list
remove = []
insert = []
num_train = 24580*0.8
cur_num_train = 0
#seperate into train and test
for key,_ in LG.nodes(data=True):
    new_edge_data = copy.deepcopy(LG.nodes()[key])
    skip = False
    for k in list(new_edge_data.keys()):
        if k not in node_feature_list:
            del new_edge_data[k]
    for k in node_feature_list:
        if k not in new_edge_data:
            skip = True
            break
    if skip == True:
        remove.append(key)
        continue
    x = []
    edge_x_y = {}
    for k,v in new_edge_data.items():
        if k == 'speed_mph_p85':
            edge_x_y['y'] = [v]
            continue
        x.append(v)
    edge_x_y['x'] = x
    if cur_num_train > num_train:
        edge_x_y['train_mask'] = False
        edge_x_y['test_mask'] = True
    else:
        edge_x_y['train_mask'] = True
        edge_x_y['test_mask'] = False 
    lg_node_attr[cur_ID] = edge_x_y
    node_relabel[key] = cur_ID
    IDs[cur_ID] = key
    cur_ID+=1
    cur_num_train+=1
    
for i in remove:
    LG.remove_node(i)
    
nx.relabel.relabel_nodes(LG,node_relabel,False)
print(lg_node_attr[20579])
nx.set_node_attributes(LG,lg_node_attr)
count = 0
for n in LG.nodes(data=True):
    count+=1
print(count)

nx.set_edge_attributes(LG,{})
for n in LG.nodes(data=True):
    print(n)
    break
print('\n')
for e in LG.edges(data=True):
    print(e)
    break

#nx.write_graphml(LG,'experiments/preprocessed/' + CITY_NAME + ".graphml")

pyData = from_networkx(LG)

{'y': [18.855], 'x': [False, 153.292], 'train_mask': False, 'test_mask': True}
20580
(20579, {'oneway': False, 'length': 153.292, 'speed_mph_p85': 18.855, 'y': [18.855], 'x': [False, 153.292], 'train_mask': False, 'test_mask': True})


(20579, 8428, {})


In [86]:
print(pyData.num_node_features)
loader = DataLoader([pyData], batch_size=1)
print(loader.dataset)
print(len(loader.dataset))

2
[Data(edge_index=[2, 60626], length=[20580], oneway=[20580], speed_mph_p85=[20580], test_mask=[20580], train_mask=[20580], x=[20580, 2], y=[20580, 1])]
1


In [85]:
    test_loader = loader = DataLoader([pyData], batch_size=1)

    # build model
    model = GNNStack(max(pyData.num_node_features, 1), 1)
    opt = optim.Adam(model.parameters(), lr=0.01)
    
    # train
    for epoch in range(1000):
        total_loss = 0
        model.train()
        for batch in loader:
            print(batch.train_mask, '----')
            opt.zero_grad()
            pred = model(batch)
            label = batch.y
            pred = pred[batch.train_mask]
            label = label[batch.train_mask]
            loss = model.loss(pred, label)
            loss.backward()
            opt.step()
            total_loss += loss.item() * batch.num_graphs
        total_loss /= len(loader.dataset)
        #writer.add_scalar("loss", total_loss, epoch)

        if epoch % 10 == 0:
            test_acc = test(test_loader, model)
            print("Epoch {}. Loss: {:.4f}. Test accuracy: {:.4f}".format(
                epoch, total_loss, test_acc))
            #writer.add_scalar("test accuracy", test_acc, epoch)

    #return model


tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[-0.6908],
        [-0.6006],
        [-0.6006],
        ...,
        [-0.6006],
        [-0.6908],
        [-0.6006]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 0. Loss: 535.1110. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[-0.5832],
        [-0.5832],
        [-0.5832],
        ...,
        [-0.5832],
        [-0.6808],
        [-0.6808]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[-0.5654],
        [-0.5654],
        [-0.5654],
        ...,
        [-0.5654],
        [-0.6708],
        [-0.6708]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
  

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[-0.0949],
        [-0.4511],
        [-0.0949],
        ...,
        [-0.4511],
        [-0.4511],
        [-0.0949]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[-0.0693],
        [-0.0693],
        [-0.0693],
        ...,
        [-0.0693],
        [-0.4411],
        [-0.0693]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[-0.4312],
        [-0.0433],
        [-0.0433],
        ...,
        [-0.0433],
        [-0.0433],
        [-0.0433]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 0.6456],
        [ 0.6456],
        [ 0.6456],
        ...,
        [ 0.6456],
        [-0.2133],
        [ 0.6456]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 0.6826],
        [ 0.6826],
        [ 0.6826],
        ...,
        [-0.2034],
        [ 0.6826],
        [ 0.6826]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[-0.1936],
        [ 0.7202],
        [ 0.7202],
        ...,
        [-0.1936],
        [ 0.7202],
        [ 0.7202]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[1.6850],
        [1.6850],
        [1.6850],
        ...,
        [1.6850],
        [1.6850],
        [0.0208]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[0.0304],
        [1.7353],
        [0.0304],
        ...,
        [1.7353],
        [1.7353],
        [0.0304]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[1.7861],
        [1.7861],
        [1.7861],
        ...,
        [1.7861],
        [1.7861],
        [1.7861]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[3.0485],
        [3.0485],
        [0.2492],
        ...,
        [3.0485],
        [0.2492],
        [0.2492]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[3.1123],
        [3.1123],
        [3.1123],
        ...,
        [3.1123],
        [3.1123],
        [3.1123]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[3.1766],
        [3.1766],
        [3.1766],
        ...,
        [3.1766],
        [3.1766],
        [0.2679]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[4.7219],
        [0.4697],
        [4.7219],
        ...,
        [4.7219],
        [0.4697],
        [4.7219]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 120. Loss: 364.5595. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[4.7979],
        [4.7979],
        [0.4787],
        ...,
        [0.4787],
        [4.7979],
        [0.4787]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[4.8743],
        [4.8743],
        [4.8743],
        ...,
        [4.8743],
        [4.8743],
        [4.8743]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[6.6637],
        [0.6801],
        [6.6637],
        ...,
        [6.6637],
        [6.6637],
        [0.6801]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[6.7495],
        [0.6886],
        [6.7495],
        ...,
        [6.7495],
        [6.7495],
        [0.6886]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[0.6971],
        [0.6971],
        [6.8356],
        ...,
        [6.8356],
        [6.8356],
        [6.8356]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[0.8782],
        [8.8017],
        [0.8782],
        ...,
        [8.8017],
        [8.8017],
        [8.8017]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[8.8938],
        [8.8938],
        [0.8862],
        ...,
        [0.8862],
        [8.8938],
        [8.8938]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[8.9860],
        [0.8941],
        [8.9860],
        ...,
        [8.9860],
        [8.9860],
        [8.9860]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[11.0421],
        [11.0421],
        [11.0421],
        ...,
        [11.0421],
        [11.0421],
        [11.0421]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[11.1359],
        [11.1359],
        [11.1359],
        ...,
        [11.1359],
        [ 1.0694],
        [ 1.0694]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[11.2296],
        [11.2296],
        [ 1.0767],
        ...,
        [11.2296],
        [11.2296],
        [11.2296]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[13.2660],
        [13.2660],
        [ 1.2301],
        ...,
        [13.2660],
        [ 1.2301],
        [13.2660]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[13.3564],
        [ 1.2367],
        [ 1.2367],
        ...,
        [ 1.2367],
        [13.3564],
        [13.3564]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[13.4466],
        [ 1.2433],
        [13.4466],
        ...,
        [ 1.2433],
        [13.4466],
        [13.4466]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 1.3817],
        [15.3488],
        [15.3488],
        ...,
        [15.3488],
        [ 1.3817],
        [ 1.3817]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 240. Loss: 172.4683. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[15.4308],
        [15.4308],
        [15.4308],
        ...,
        [ 1.3876],
        [15.4308],
        [15.4308]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 1.3936],
        [15.5123],
        [15.5123],
        ...,
        [15.5123],
        [15.5123],
        [15.5123]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],


tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[17.1795],
        [17.1795],
        [17.1795],
        ...,
        [ 1.5171],
        [17.1795],
        [17.1795]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 1.5224],
        [17.2489],
        [17.2489],
        ...,
        [17.2489],
        [17.2489],
        [ 1.5224]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[17.3177],
        [ 1.5277],
        [17.3177],
        ...,
        [17.3177],
        [17.3177],
        [17.3177]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 1.6379],
        [18.6779],
        [ 1.6379],
        ...,
        [ 1.6379],
        [18.6779],
        [18.6779]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[18.7323],
        [18.7323],
        [18.7323],
        ...,
        [ 1.6427],
        [18.7323],
        [ 1.6427]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[18.7862],
        [18.7862],
        [18.7862],
        ...,
        [18.7862],
        [18.7862],
        [18.7862]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[19.8115],
        [ 1.7466],
        [ 1.7466],
        ...,
        [19.8115],
        [19.8115],
        [19.8115]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[19.8511],
        [19.8511],
        [19.8511],
        ...,
        [ 1.7509],
        [19.8511],
        [19.8511]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[19.8902],
        [ 1.7552],
        [19.8902],
        ...,
        [19.8902],
        [19.8902],
        [ 1.7552]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[20.6119],
        [20.6119],
        [20.6119],
        ...,
        [20.6119],
        [20.6119],
        [ 1.8460]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 1.8500],
        [20.6388],
        [20.6388],
        ...,
        [20.6388],
        [20.6388],
        [ 1.8500]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[20.6653],
        [20.6653],
        [20.6653],
        ...,
        [ 1.8540],
        [20.6653],
        [20.6653]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.1350],
        [21.1350],
        [21.1350],
        ...,
        [ 1.9388],
        [21.1350],
        [21.1350]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 360. Loss: 135.5448. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.1518],
        [21.1518],
        [ 1.9425],
        ...,
        [ 1.9425],
        [ 1.9425],
        [21.1518]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.1683],
        [21.1683],
        [21.1683],
        ...,
        [21.1683],
        [ 1.9463],
        [ 1.9463]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],


tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 2.0283],
        [ 2.0283],
        [ 2.0283],
        ...,
        [21.4546],
        [ 2.0283],
        [ 2.0283]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.4647],
        [ 2.0320],
        [21.4647],
        ...,
        [21.4647],
        [21.4647],
        [21.4647]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 2.0357],
        [21.4745],
        [ 2.0357],
        ...,
        [21.4745],
        [21.4745],
        [ 2.0357]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.6405],
        [21.6405],
        [21.6405],
        ...,
        [21.6405],
        [21.6405],
        [21.6405]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 2.1201],
        [ 2.1201],
        [21.6461],
        ...,
        [ 2.1201],
        [ 2.1201],
        [21.6461]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.6515],
        [21.6515],
        [21.6515],
        ...,
        [21.6515],
        [21.6515],
        [21.6515]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.7428],
        [ 2.2045],
        [21.7428],
        ...,
        [21.7428],
        [21.7428],
        [21.7428]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.7460],
        [21.7460],
        [21.7460],
        ...,
        [ 2.2082],
        [21.7460],
        [21.7460]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.7490],
        [21.7490],
        [ 2.2119],
        ...,
        [21.7490],
        [21.7490],
        [ 2.2119]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.7976],
        [21.7976],
        [21.7976],
        ...,
        [21.7976],
        [21.7976],
        [21.7976]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.7991],
        [21.7991],
        [ 2.2974],
        ...,
        [21.7991],
        [21.7991],
        [21.7991]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8005],
        [21.8005],
        [21.8005],
        ...,
        [21.8005],
        [21.8005],
        [21.8005]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8213],
        [21.8213],
        [21.8213],
        ...,
        [21.8213],
        [21.8213],
        [21.8213]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 480. Loss: 128.7346. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8220],
        [21.8220],
        [21.8220],
        ...,
        [21.8220],
        [21.8220],
        [21.8220]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8226],
        [21.8226],
        [21.8226],
        ...,
        [21.8226],
        [21.8226],
        [21.8226]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],


tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 2.4757],
        [ 2.4757],
        [21.8341],
        ...,
        [21.8341],
        [21.8341],
        [21.8341]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8344],
        [21.8344],
        [21.8344],
        ...,
        [ 2.4796],
        [ 2.4796],
        [21.8344]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8347],
        [ 2.4835],
        [21.8347],
        ...,
        [ 2.4835],
        [21.8347],
        [ 2.4835]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8399],
        [21.8399],
        [21.8399],
        ...,
        [21.8399],
        [ 2.5694],
        [21.8399]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8398],
        [ 2.5733],
        [ 2.5733],
        ...,
        [21.8398],
        [21.8398],
        [21.8398]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8398],
        [21.8398],
        [21.8398],
        ...,
        [ 2.5772],
        [21.8398],
        [21.8398]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8409],
        [21.8409],
        [ 2.6646],
        ...,
        [ 2.6646],
        [ 2.6646],
        [21.8409]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8409],
        [21.8409],
        [21.8409],
        ...,
        [ 2.6686],
        [21.8409],
        [21.8409]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8409],
        [ 2.6726],
        [ 2.6726],
        ...,
        [21.8409],
        [ 2.6726],
        [21.8409]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8391],
        [ 2.7620],
        [ 2.7620],
        ...,
        [21.8391],
        [21.8391],
        [21.8391]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8390],
        [21.8390],
        [21.8390],
        ...,
        [ 2.7661],
        [ 2.7661],
        [21.8390]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8390],
        [21.8390],
        [21.8390],
        ...,
        [21.8390],
        [21.8390],
        [21.8390]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 2.8611],
        [21.8394],
        [ 2.8611],
        ...,
        [21.8394],
        [21.8394],
        [ 2.8611]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 600. Loss: 127.7564. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 2.8652],
        [ 2.8652],
        [21.8394],
        ...,
        [ 2.8652],
        [ 2.8652],
        [21.8394]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8393],
        [21.8393],
        [21.8393],
        ...,
        [21.8393],
        [21.8393],
        [21.8393]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],


tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8423],
        [21.8423],
        [21.8423],
        ...,
        [21.8423],
        [ 2.9617],
        [21.8423]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8425],
        [21.8425],
        [21.8425],
        ...,
        [ 2.9659],
        [21.8425],
        [ 2.9659]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 2.9701],
        [21.8427],
        [21.8427],
        ...,
        [ 2.9701],
        [21.8427],
        [21.8427]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8408],
        [ 3.0638],
        [ 3.0638],
        ...,
        [21.8408],
        [21.8408],
        [21.8408]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8405],
        [21.8405],
        [21.8405],
        ...,
        [ 3.0681],
        [21.8405],
        [21.8405]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8403],
        [21.8403],
        [21.8403],
        ...,
        [21.8403],
        [21.8403],
        [21.8403]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8376],
        [ 3.1673],
        [ 3.1673],
        ...,
        [21.8376],
        [21.8376],
        [21.8376]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8375],
        [ 3.1717],
        [ 3.1717],
        ...,
        [21.8375],
        [21.8375],
        [21.8375]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 3.1761],
        [21.8374],
        [21.8374],
        ...,
        [21.8374],
        [ 3.1761],
        [21.8374]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8388],
        [21.8388],
        [ 3.2729],
        ...,
        [21.8388],
        [21.8388],
        [21.8388]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 3.2773],
        [21.8388],
        [21.8388],
        ...,
        [21.8388],
        [21.8388],
        [ 3.2773]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8388],
        [21.8388],
        [21.8388],
        ...,
        [ 3.2817],
        [ 3.2817],
        [21.8388]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8361],
        [ 3.3796],
        [ 3.3796],
        ...,
        [21.8361],
        [21.8361],
        [21.8361]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 720. Loss: 121.6896. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8361],
        [21.8361],
        [21.8361],
        ...,
        [21.8361],
        [21.8361],
        [21.8361]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8361],
        [21.8361],
        [21.8361],
        ...,
        [21.8361],
        [21.8361],
        [21.8361]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],


tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8290],
        [21.8290],
        [21.8290],
        ...,
        [21.8290],
        [ 3.4874],
        [21.8290]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 3.4920],
        [21.8290],
        [21.8290],
        ...,
        [ 3.4920],
        [21.8290],
        [21.8290]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 3.4965],
        [21.8290],
        [ 3.4965],
        ...,
        [21.8290],
        [21.8290],
        [ 3.4965]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8317],
        [21.8317],
        [21.8317],
        ...,
        [ 3.5968],
        [21.8317],
        [21.8317]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8317],
        [ 3.6014],
        [21.8317],
        ...,
        [21.8317],
        [21.8317],
        [ 3.6014]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8316],
        [21.8316],
        [21.8316],
        ...,
        [21.8316],
        [21.8316],
        [ 3.6060]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8325],
        [ 3.7075],
        [ 3.7075],
        ...,
        [21.8325],
        [21.8325],
        [ 3.7075]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 3.7122],
        [ 3.7122],
        [21.8324],
        ...,
        [21.8324],
        [21.8324],
        [21.8324]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8324],
        [21.8324],
        [21.8324],
        ...,
        [21.8324],
        [21.8324],
        [ 3.7168]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8332],
        [21.8332],
        [21.8332],
        ...,
        [21.8332],
        [21.8332],
        [ 3.8194]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8332],
        [21.8332],
        [21.8332],
        ...,
        [ 3.8241],
        [21.8332],
        [21.8332]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8332],
        [21.8332],
        [21.8332],
        ...,
        [21.8332],
        [ 3.8288],
        [ 3.8288]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8332],
        [21.8332],
        [21.8332],
        ...,
        [21.8332],
        [21.8332],
        [21.8332]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 840. Loss: 115.6938. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8332],
        [21.8332],
        [21.8332],
        ...,
        [ 3.9371],
        [21.8332],
        [21.8332]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8334],
        [ 3.9419],
        [21.8334],
        ...,
        [ 3.9419],
        [21.8334],
        [21.8334]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],


tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8332],
        [ 4.0467],
        [21.8332],
        ...,
        [21.8332],
        [21.8332],
        [21.8332]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 4.0515],
        [21.8330],
        [21.8330],
        ...,
        [21.8330],
        [ 4.0515],
        [21.8330]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8329],
        [21.8329],
        [21.8329],
        ...,
        [21.8329],
        [21.8329],
        [ 4.0563]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8293],
        [21.8293],
        [21.8293],
        ...,
        [ 4.1617],
        [21.8293],
        [21.8293]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 4.1665],
        [21.8292],
        [21.8292],
        ...,
        [ 4.1665],
        [ 4.1665],
        [21.8292]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8292],
        [21.8292],
        [21.8292],
        ...,
        [21.8292],
        [21.8292],
        [21.8292]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8269],
        [21.8269],
        [21.8269],
        ...,
        [21.8269],
        [21.8269],
        [21.8269]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 4.2827],
        [21.8267],
        [21.8267],
        ...,
        [ 4.2827],
        [ 4.2827],
        [21.8267]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 4.2876],
        [ 4.2876],
        [21.8267],
        ...,
        [21.8267],
        [21.8267],
        [21.8267]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8271],
        [21.8271],
        [21.8271],
        ...,
        [21.8271],
        [21.8271],
        [21.8271]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8271],
        [21.8271],
        [21.8271],
        ...,
        [21.8271],
        [21.8271],
        [21.8271]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8273],
        [21.8273],
        [21.8273],
        ...,
        [21.8273],
        [ 4.4053],
        [21.8273]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 4.5134],
        [21.8253],
        [21.8253],
        ...,
        [21.8253],
        [21.8253],
        [21.8253]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



Epoch 960. Loss: 111.0601. Test accuracy: 0.0000
tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8252],
        [21.8252],
        [21.8252],
        ...,
        [21.8252],
        [ 4.5183],
        [21.8252]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[ 4.5232],
        [21.8253],
        [21.8253],
        ...,
        [21.8253],
        [21.8253],
        [21.8253]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],


tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8278],
        [21.8278],
        [21.8278],
        ...,
        [21.8278],
        [21.8278],
        [ 4.6324]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8278],
        [21.8278],
        [21.8278],
        ...,
        [ 4.6373],
        [21.8278],
        [21.8278]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080],
        [26.5269],
        [13.1970]])
HI



tensor([False,  True,  True,  ...,  True,  True,  True]) ----
tensor([[21.8279],
        [ 4.6423],
        [21.8279],
        ...,
        [21.8279],
        [21.8279],
        [21.8279]], grad_fn=<IndexBackward>)
tensor([[20.7269],
        [15.5725],
        [28.0510],
        ...,
        [18.9080]

In [61]:
def test(loader, model, is_validation=False):
    model.eval()

    correct = 0
    for data in loader:
        with torch.no_grad():
            pred = model(data)
            pred = pred.argmax(dim=1)
            label = data.y

        mask = data.val_mask if is_validation else data.test_mask
        # node classification: only evaluate on nodes in test set
        pred = pred[mask]
        label = data.y[mask]
        #print(label, pred)
        correct += pred.eq(label).sum().item()
    total = 0
    for data in loader.dataset:
        total += torch.sum(data.test_mask).item()
    return correct / total